const DB_NAME='sidequest-local';
const DB_VERSION=1;
const state={tasks:[],progress:[],filter:'active',xp:680,timerSeconds:1500,timerId:null,weekAnchor:'2026-08-31',viewWeek:'A',viewDay:'Monday',editingTimetable:false,timetable:{A:{},B:{}},settingsUpdatedAt:0};
let syncModulePromise;
let syncTimer;
let syncRunning=false;
const subjects=[['Maths',72,'#57ead7'],['Reader',100,'#aa79ff'],['Science',35,'#d9f65a']];
const schoolDays=['Monday','Tuesday','Wednesday','Thursday','Friday'];
const importedTimetable={A:{},B:{}};
const legacyDemoTitles=new Set(['Finish Sparx Science','English character analysis','History source questions']);

function uid(){return crypto.randomUUID?.()??`${Date.now()}-${Math.random()}`}
function openDB(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('tasks'))db.createObjectStore('tasks',{keyPath:'id'});if(!db.objectStoreNames.contains('settings'))db.createObjectStore('settings',{keyPath:'key'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function getAll(store){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(store,'readonly');const req=tx.objectStore(store).getAll();req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function put(store,value){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).put(value);tx.oncomplete=()=>{resolve();if(store==='tasks'&&!syncRunning)queueSync()};tx.onerror=()=>reject(tx.error)})}
function loadSync(){return syncModulePromise??=import('./sync.js?v=12')}
function queueSync(){clearTimeout(syncTimer);syncTimer=setTimeout(()=>performSync(true),1500)}
async function markSettingsDirty(){state.settingsUpdatedAt=Date.now();await put('settings',{key:'settingsUpdatedAt',value:state.settingsUpdatedAt});queueSync()}
function notificationPrefs(){return{morningEnabled:document.querySelector('#morning-enabled').checked,morningTime:document.querySelector('#morning-time').value,eveningEnabled:document.querySelector('#evening-enabled').checked,eveningTime:document.querySelector('#evening-time').value,sparxEnabled:document.querySelector('#sparx-enabled').checked,sparxTime:document.querySelector('#sparx-time').value}}
function settingsPayload(){return{xp:state.xp,progress:state.progress,timetable:state.timetable,weekAnchor:state.weekAnchor,accent:document.querySelector('#accent-select').value,reduceMotion:document.querySelector('#motion-toggle').checked,privateNotifications:document.querySelector('#privacy-toggle').checked,notificationPrefs:notificationPrefs()}}
async function applyCloudSettings(payload,updatedAt){state.xp=payload.xp??state.xp;state.progress=payload.progress??state.progress;state.timetable=payload.timetable??state.timetable;state.weekAnchor=payload.weekAnchor??state.weekAnchor;state.settingsUpdatedAt=updatedAt;await Promise.all(Object.entries({...payload,settingsUpdatedAt:updatedAt}).map(([key,value])=>put('settings',{key,value})));applySettings(payload)}
function setAccountStatus(message,error=false){const node=document.querySelector('#account-status');node.textContent=message;node.style.color=error?'var(--danger)':'var(--accent-2)'}
async function refreshAccount(){try{const api=await loadSync();const user=await api.currentUser();document.querySelector('#signed-out-panel').hidden=Boolean(user);document.querySelector('#signed-in-panel').hidden=!user;document.querySelector('#account-user').textContent=user?.email??'';document.querySelector('#profile-button').classList.toggle('synced',Boolean(user));setAccountStatus(user?'Connected · ready to sync':'Sign in or create an account');return user}catch(error){setAccountStatus(error.message,true);return null}}
async function performSync(silent=false){if(syncRunning||!navigator.onLine)return;syncRunning=true;try{const api=await loadSync();const result=await api.syncTasks(state.tasks,async incoming=>{const existing=state.tasks.find(task=>task.id===incoming.id);if(existing)Object.assign(existing,incoming);else state.tasks.push(incoming);await put('tasks',incoming)});const settingsResult=await api.syncSettings(settingsPayload(),state.settingsUpdatedAt);if(settingsResult.direction==='download')await applyCloudSettings(settingsResult.payload,settingsResult.updatedAt);render();document.querySelector('#profile-button').classList.add('synced');if(!silent)setAccountStatus(`Synced · ${result.uploaded} tasks up, ${result.downloaded} down · settings ${settingsResult.direction}ed`)}catch(error){if(!silent)setAccountStatus(error.message,true)}finally{syncRunning=false}}

async function seed(){state.tasks=await getAll('tasks');const saved=await getAll('settings');const settings=Object.fromEntries(saved.map(x=>[x.key,x.value]));state.xp=settings.xp??680;state.progress=settings.progress??subjects.map(([name,value,color])=>({name,value,color}));state.weekAnchor=settings.weekAnchor??'2026-08-31';const hasSavedLessons=schoolDays.some(day=>(settings.timetable?.A?.[day]?.length??0)+(settings.timetable?.B?.[day]?.length??0)>0);state.timetable=hasSavedLessons?settings.timetable:structuredClone(importedTimetable);state.settingsUpdatedAt=settings.settingsUpdatedAt??(hasSavedLessons?Date.now():0);const now=new Date();const today=now.toLocaleDateString('en-GB',{weekday:'long'});const afterSchool=now.getHours()*60+now.getMinutes()>=915;const initialDate=!schoolDays.includes(today)||afterSchool?nextSchoolDate(now):now;state.viewWeek=currentSchoolWeek(initialDate??now);state.viewDay=(initialDate??now).toLocaleDateString('en-GB',{weekday:'long'});applySettings(settings);if(!settings.settingsUpdatedAt)await put('settings',{key:'settingsUpdatedAt',value:state.settingsUpdatedAt});if(!hasSavedLessons)await put('settings',{key:'timetable',value:state.timetable});const demos=state.tasks.filter(task=>!task.deleted&&legacyDemoTitles.has(task.title));for(const task of demos){task.deleted=true;task.deletedAt=Date.now();task.updatedAt=task.deletedAt;await put('tasks',task)}render()}

function applySettings(settings){const accent=settings.accent??'violet';document.documentElement.dataset.accent=accent;const colors={violet:'#9468ff',cyan:'#36d9ec',lime:'#b9dc39',rose:'#ff629e'};document.documentElement.style.setProperty('--accent',colors[accent]);document.querySelector('#accent-select').value=accent;document.querySelector('#motion-toggle').checked=Boolean(settings.reduceMotion);document.body.classList.toggle('reduce-motion',Boolean(settings.reduceMotion));document.querySelector('#privacy-toggle').checked=settings.privateNotifications!==false;const prefs=settings.notificationPrefs??{};document.querySelector('#morning-enabled').checked=prefs.morningEnabled!==false;document.querySelector('#morning-time').value=prefs.morningTime??'07:00';document.querySelector('#evening-enabled').checked=prefs.eveningEnabled!==false;document.querySelector('#evening-time').value=prefs.eveningTime??'19:00';document.querySelector('#sparx-enabled').checked=prefs.sparxEnabled!==false;document.querySelector('#sparx-time').value=prefs.sparxTime??'18:00';updateNotificationState()}
function updateNotificationState(){const badge=document.querySelector('#notification-state');const permission='Notification'in window?Notification.permission:'unsupported';badge.textContent=permission==='granted'?'Enabled':permission==='denied'?'Blocked':permission==='unsupported'?'Unsupported':'Not enabled';badge.classList.toggle('enabled',permission==='granted')}
function activeTasks(){return state.tasks.filter(t=>!t.deleted)}
function dateText(date){const due=new Date(`${date}T23:59:59`);const days=Math.ceil((due-new Date())/86400000);if(days<0)return `${Math.abs(days)}d overdue`;if(days===0)return 'due today';if(days===1)return 'due tomorrow';return `due ${due.toLocaleDateString(undefined,{weekday:'short',day:'numeric',month:'short'})}`}
function taskHTML(task){return `<article class="task ${task.completed?'done':''}" data-task="${task.id}"><button class="task-check" type="button" aria-label="${task.completed?'Reopen':'Complete'} ${escapeHTML(task.title)}">${task.completed?'✓':''}</button><div class="task-copy" role="button" aria-label="Edit ${escapeHTML(task.title)}"><strong>${escapeHTML(task.title)}</strong><span>${escapeHTML(task.subject)} · ${dateText(task.due)} · ${task.minutes} min</span></div><span class="task-xp">+${task.xp} XP</span><button class="task-edit" type="button" aria-label="Edit ${escapeHTML(task.title)}">✎</button></article>`}
function escapeHTML(value){const node=document.createElement('div');node.textContent=value;return node.innerHTML}
function currentSchoolWeek(date=new Date()){const anchor=new Date(`${state.weekAnchor}T12:00:00`);const target=new Date(date);target.setHours(12,0,0,0);const weeks=Math.floor((target-anchor)/604800000);return Math.abs(weeks)%2===0?'A':'B'}
function lessonParts(line){const match=line.match(/^(\d{2}:\d{2})\s+(.+?)(?:\s+·\s+(.+))?$/);return match?{time:match[1],name:match[2],room:match[3]??'—'}:{time:'',name:line,room:'—'}}
function scheduleForDate(date){const day=date.toLocaleDateString('en-GB',{weekday:'long'});if(!schoolDays.includes(day))return[];return(state.timetable[currentSchoolWeek(date)]?.[day]??[]).map(line=>({...lessonParts(line),line}))}
function nextSchoolDate(after,includeToday=false){for(let offset=includeToday?0:1;offset<9;offset++){const date=new Date(after);date.setDate(date.getDate()+offset);if(scheduleForDate(date).length)return date}return null}
function renderHomeSchedule(){const now=new Date();const currentMinutes=now.getHours()*60+now.getMinutes();const todayName=now.toLocaleDateString('en-GB',{weekday:'long'});const rolled=!schoolDays.includes(todayName)||currentMinutes>=915;const displayDate=rolled?nextSchoolDate(now):now;const displayLessons=displayDate?scheduleForDate(displayDate):[];const remaining=rolled?displayLessons:displayLessons.filter(item=>{const [h,m]=item.time.split(':').map(Number);return h*60+m>currentMinutes});const week=currentSchoolWeek(displayDate??now);document.querySelector('#home-week-label').textContent=`Week ${week}`;const nextLesson=remaining[0];const nextLabel=rolled?displayDate?.toLocaleDateString('en-GB',{weekday:'long'})??'Next lesson':'Next lesson';document.querySelector('#next-lesson-label').textContent=nextLabel;document.querySelector('#next-lesson-name').textContent=nextLesson?.name??'Nothing scheduled';document.querySelector('#next-lesson-meta').textContent=nextLesson?`${nextLesson.time} · ${nextLesson.room} · Week ${week}`:'Timetable clear';const following=displayDate?nextSchoolDate(displayDate):null;const followingLessons=following?scheduleForDate(following):[];const firstFollowing=followingLessons.find(item=>item.name!=='Tutor/Assembly')??followingLessons[0];document.querySelector('#next-day-label').textContent=following?.toLocaleDateString('en-GB',{weekday:'long'})??'Next school day';document.querySelector('#next-day-name').textContent=firstFollowing?.name??'Nothing scheduled';document.querySelector('#next-day-meta').textContent=firstFollowing?`${firstFollowing.time} · ${firstFollowing.room} · Week ${currentSchoolWeek(following)}`:'Timetable clear';document.querySelector('#today-strip').innerHTML=displayLessons.length?displayLessons.map(item=>`<span class="mini-lesson ${remaining[0]?.line===item.line?'next':''}">${item.time} · ${escapeHTML(item.name)}</span>`).join(''):'<span class="mini-lesson">No lessons scheduled</span>'}
function renderTimetable(){const actual=currentSchoolWeek();const today=new Date().toLocaleDateString('en-GB',{weekday:'long'});document.querySelector('#current-week-label').textContent=`Week ${actual}`;document.querySelector('#calendar-week-note').textContent=`Currently Week ${actual}`;document.querySelectorAll('[data-week]').forEach(button=>button.classList.toggle('active',button.dataset.week===state.viewWeek));const lessons=state.timetable[state.viewWeek]?.[state.viewDay]??[];const tabs=schoolDays.map(day=>`<button class="day-tab ${day===state.viewDay?'active':''} ${state.viewWeek===actual&&day===today?'today':''}" type="button" data-day="${day}">${day.slice(0,3)}</button>`).join('');let content;if(state.editingTimetable){content=`<div class="timetable-editor"><textarea id="day-editor" aria-label="Edit ${state.viewDay} lessons">${escapeHTML(lessons.join('\n'))}</textarea><div class="editor-actions"><button class="secondary-button" id="cancel-day-edit" type="button">Cancel</button><button class="primary-button" id="save-day-edit" type="button">Save day</button></div></div>`}else{content=lessons.length?lessons.map(line=>{const item=lessonParts(line);return `<div class="lesson-row"><time class="lesson-time">${escapeHTML(item.time)}</time><strong class="lesson-name">${escapeHTML(item.name)}</strong><span class="lesson-room">${escapeHTML(item.room)}</span></div>`}).join(''):'<p class="empty-state">No lessons saved for this day.</p>'}document.querySelector('#timetable-grid').innerHTML=`<div class="day-tabs">${tabs}</div><div class="day-schedule"><div class="day-schedule-head"><strong>${state.viewDay} · Week ${state.viewWeek}</strong><button class="edit-day" id="edit-day" type="button">${state.editingTimetable?'Editing':'Edit day'}</button></div>${content}</div>`;document.querySelectorAll('[data-day]').forEach(button=>button.addEventListener('click',()=>{state.viewDay=button.dataset.day;state.editingTimetable=false;renderTimetable()}));document.querySelector('#edit-day')?.addEventListener('click',()=>{state.editingTimetable=true;renderTimetable()});document.querySelector('#cancel-day-edit')?.addEventListener('click',()=>{state.editingTimetable=false;renderTimetable()});document.querySelector('#save-day-edit')?.addEventListener('click',async()=>{state.timetable[state.viewWeek][state.viewDay]=document.querySelector('#day-editor').value.split(/[\n,]+/).map(x=>x.trim()).filter(Boolean);await put('settings',{key:'timetable',value:state.timetable});state.editingTimetable=false;renderTimetable();flash(`${state.viewDay} saved`)})}
function render(){const tasks=activeTasks().sort((a,b)=>a.due.localeCompare(b.due));document.querySelector('#task-list').innerHTML=tasks.filter(t=>!t.completed).slice(0,4).map(taskHTML).join('');document.querySelector('#empty-state').hidden=tasks.some(t=>!t.completed);document.querySelector('#remaining-count').textContent=`${tasks.filter(t=>!t.completed).length} remaining`;document.querySelector('#quest-list').innerHTML=tasks.filter(t=>state.filter==='all'||(state.filter==='completed'?t.completed:!t.completed)).map(taskHTML).join('')||'<p class="empty-state">Nothing in this section.</p>';document.querySelector('#calendar-list').innerHTML=tasks.filter(t=>!t.completed).map(t=>`<div class="timeline-day"><strong>${new Date(`${t.due}T12:00`).toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'})}</strong><span>${escapeHTML(t.title)} · ${escapeHTML(t.subject)}</span></div>`).join('')||'<p class="empty-state">Your calendar is clear.</p>';renderProgress();renderXP();renderTimetable();renderHomeSchedule();bindTaskButtons()}
function renderProgress(){document.querySelector('#progress-grid').innerHTML=state.progress.map((p,i)=>`<article class="progress-card"><div class="progress-ring" style="--value:${p.value}%;--ring-color:${p.color}">${p.value===100?'Done':`${p.value}%`}</div><strong>${p.name}</strong><input type="range" min="0" max="100" step="5" value="${p.value}" data-progress="${i}" aria-label="${p.name} completion"></article>`).join('');document.querySelectorAll('[data-progress]').forEach(input=>input.addEventListener('input',async()=>{state.progress[Number(input.dataset.progress)].value=Number(input.value);await put('settings',{key:'progress',value:state.progress});renderProgress()}))}
function renderXP(){document.querySelector('#xp-label').textContent=`${state.xp} / 1000 XP`;document.querySelector('#xp-bar').style.width=`${Math.min(100,state.xp/10)}%`}
function bindTaskButtons(){document.querySelectorAll('.task-check').forEach(button=>button.addEventListener('click',async()=>{const task=state.tasks.find(t=>t.id===button.closest('.task').dataset.task);task.completed=!task.completed;task.updatedAt=Date.now();state.xp+=task.completed?task.xp:-task.xp;await Promise.all([put('tasks',task),put('settings',{key:'xp',value:state.xp})]);render();flash(task.completed?`Quest complete · +${task.xp} XP`:'Quest reopened')}));document.querySelectorAll('.task-edit,.task-copy').forEach(button=>button.addEventListener('click',()=>openTaskDialog(button.closest('.task').dataset.task)))}
function openTaskDialog(id=null){const form=document.querySelector('#task-form');form.reset();const task=id?state.tasks.find(t=>t.id===id):null;document.querySelector('#task-dialog-title').textContent=task?'Edit quest':'New quest';document.querySelector('#delete-task').hidden=!task;document.querySelector('#task-id').value=task?.id??'';document.querySelector('#task-title').value=task?.title??'';document.querySelector('#task-subject').value=task?.subject??'';document.querySelector('#task-minutes').value=task?.minutes??30;document.querySelector('#task-due').value=task?.due??new Date(Date.now()+86400000).toISOString().slice(0,10);document.querySelector('#task-dialog').showModal()}
function flash(message){const pill=document.querySelector('#status-pill');pill.textContent=message;pill.classList.add('show');clearTimeout(flash.timeout);flash.timeout=setTimeout(()=>pill.classList.remove('show'),1800)}

document.querySelector('#today-label').textContent=`${new Date().toLocaleDateString(undefined,{weekday:'long'})} · Command centre`;
document.querySelector('#profile-button').addEventListener('click',async()=>{document.querySelector('#account-dialog').showModal();setAccountStatus(navigator.onLine?'Checking account…':'Offline · local data is still available');await refreshAccount()});
document.querySelector('#close-account').addEventListener('click',()=>document.querySelector('#account-dialog').close());
document.querySelector('#account-form').addEventListener('submit',async event=>{event.preventDefault();setAccountStatus('Signing in…');try{const api=await loadSync();await api.signIn(document.querySelector('#account-email').value.trim(),document.querySelector('#account-password').value);await refreshAccount();setAccountStatus('Signed in · starting sync');await performSync()}catch(error){setAccountStatus(error.message,true)}});
document.querySelector('#signup-button').addEventListener('click',async()=>{const email=document.querySelector('#account-email').value.trim();const password=document.querySelector('#account-password').value;if(!email||password.length<8){setAccountStatus('Enter an email and a password of at least 8 characters.',true);return}setAccountStatus('Creating account…');try{const api=await loadSync();const result=await api.signUp(email,password);if(result.session){await refreshAccount();setAccountStatus('Account created · starting sync');await performSync()}else setAccountStatus('Check your email to confirm the account, then sign in.')}catch(error){setAccountStatus(error.message,true)}});
document.querySelector('#sync-button').addEventListener('click',()=>performSync());
document.querySelector('#signout-button').addEventListener('click',async()=>{try{const api=await loadSync();await api.signOut();await refreshAccount();setAccountStatus('Signed out. Local data remains on this device.')}catch(error){setAccountStatus(error.message,true)}});
document.querySelectorAll('[data-nav]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-nav]').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('.page').forEach(page=>page.classList.toggle('active',page.dataset.page===button.dataset.nav));document.querySelector('.fab').hidden=button.dataset.nav==='focus'||button.dataset.nav==='workshop'}));
document.querySelectorAll('[data-open-task]').forEach(button=>button.addEventListener('click',()=>openTaskDialog()));
document.querySelector('#task-form').addEventListener('submit',async event=>{if(event.submitter?.value==='cancel')return;event.preventDefault();const id=document.querySelector('#task-id').value;const existing=id?state.tasks.find(t=>t.id===id):null;const minutes=Number(document.querySelector('#task-minutes').value);const task={...(existing??{}),id:existing?.id??uid(),title:document.querySelector('#task-title').value.trim(),subject:document.querySelector('#task-subject').value.trim(),due:document.querySelector('#task-due').value,minutes,completed:existing?.completed??false,xp:Math.max(20,Math.round(minutes*2)),updatedAt:Date.now(),deleted:false};if(existing)Object.assign(existing,task);else state.tasks.push(task);await put('tasks',task);document.querySelector('#task-dialog').close();render();flash(existing?'Quest updated':'Quest added')});
document.querySelector('#delete-task').addEventListener('click',async()=>{const task=state.tasks.find(t=>t.id===document.querySelector('#task-id').value);if(!task||!confirm(`Delete “${task.title}”?`))return;task.deleted=true;task.updatedAt=Date.now();task.deletedAt=task.updatedAt;if(task.completed){state.xp-=task.xp;await put('settings',{key:'xp',value:state.xp})}await put('tasks',task);document.querySelector('#task-dialog').close();render();flash('Quest deleted · tombstone saved')});
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{state.filter=button.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===button));render()}));
document.querySelectorAll('[data-week]').forEach(button=>button.addEventListener('click',()=>{state.viewWeek=button.dataset.week;state.editingTimetable=false;renderTimetable()}));
document.querySelector('#reset-progress').addEventListener('click',async()=>{state.progress.forEach(p=>p.value=0);await put('settings',{key:'progress',value:state.progress});renderProgress();flash('New Sparx week started')});
document.querySelector('#panic-button').addEventListener('click',()=>{const next=activeTasks().filter(t=>!t.completed).sort((a,b)=>a.due.localeCompare(b.due))[0];const plan=document.querySelector('#panic-plan');plan.hidden=!plan.hidden;plan.textContent=next?`Start with “${next.title}”. Set a ${Math.min(25,next.minutes)}-minute focus timer and ignore everything else until it rings.`:'There is nothing to panic about. Somehow.'});
document.querySelector('#accent-select').addEventListener('change',async e=>{await put('settings',{key:'accent',value:e.target.value});applySettings({accent:e.target.value,reduceMotion:document.querySelector('#motion-toggle').checked,privateNotifications:document.querySelector('#privacy-toggle').checked})});
document.querySelector('#motion-toggle').addEventListener('change',async e=>{document.body.classList.toggle('reduce-motion',e.target.checked);await put('settings',{key:'reduceMotion',value:e.target.checked})});
document.querySelector('#privacy-toggle').addEventListener('change',e=>put('settings',{key:'privateNotifications',value:e.target.checked}));
document.querySelectorAll('#morning-enabled,#morning-time,#evening-enabled,#evening-time,#sparx-enabled,#sparx-time').forEach(control=>control.addEventListener('change',async()=>{await put('settings',{key:'notificationPrefs',value:notificationPrefs()});await markSettingsDirty();flash('Notification schedule saved')}));
document.querySelector('#enable-notifications').addEventListener('click',async()=>{if(!('Notification'in window)){flash('Notifications are not supported here');return}const permission=await Notification.requestPermission();updateNotificationState();flash(permission==='granted'?'Notifications enabled':'Notification permission was not granted')});
document.querySelector('#test-notification').addEventListener('click',async()=>{if(!('Notification'in window)||Notification.permission!=='granted'){flash('Enable notifications first');return}const registration=await navigator.serviceWorker.ready;registration.active?.postMessage({type:'TEST_NOTIFICATION'});flash('Test notification sent')});
document.querySelector('#export-button').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),tasks:activeTasks(),progress:state.progress,xp:state.xp},null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`sidequest-backup-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(link.href)});
document.querySelector('#import-input').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());if(!Array.isArray(data.tasks))throw new Error();state.tasks=data.tasks;state.progress=data.progress??state.progress;state.xp=data.xp??state.xp;await Promise.all([...state.tasks.map(t=>put('tasks',t)),put('settings',{key:'progress',value:state.progress}),put('settings',{key:'xp',value:state.xp})]);render();flash('Backup imported')}catch{flash('That backup could not be read')}});
function icsEscape(value){return String(value).replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;')}
function icsUnescape(value){return value.replace(/\\n/gi,'\n').replace(/\\([,;\\])/g,'$1')}
function downloadFile(name,type,contents){const blob=new Blob([contents],{type});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),0)}
function exportCalendar(){const stamp=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const events=activeTasks().filter(t=>!t.completed).map(task=>['BEGIN:VEVENT',`UID:${icsEscape(task.sourceKey??`${task.id}@sidequest.local`)}`,`DTSTAMP:${stamp}`,`DTSTART;VALUE=DATE:${task.due.replaceAll('-','')}`,`SUMMARY:${icsEscape(task.title)}`,`DESCRIPTION:${icsEscape(`Sidequest subject: ${task.subject}; estimate: ${task.minutes} minutes`)}`,'END:VEVENT'].join('\r\n'));downloadFile(`sidequest-calendar-${new Date().toISOString().slice(0,10)}.ics`,'text/calendar;charset=utf-8',['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Sidequest//School Command Centre//EN','CALSCALE:GREGORIAN',...events,'END:VCALENDAR',''].join('\r\n'));flash(`${events.length} quests exported`)}
function parseICS(text){const unfolded=text.replace(/\r?\n[ \t]/g,'');const blocks=unfolded.split(/BEGIN:VEVENT\r?\n/i).slice(1).map(x=>x.split(/\r?\nEND:VEVENT/i)[0]);return blocks.map(block=>{const fields={};for(const line of block.split(/\r?\n/)){const split=line.indexOf(':');if(split<0)continue;const rawKey=line.slice(0,split);const key=rawKey.split(';')[0].toUpperCase();if(!fields[key])fields[key]=line.slice(split+1)}const rawDate=fields.DTSTART?.match(/\d{8}/)?.[0];if(!rawDate||!fields.SUMMARY)return null;return{uid:fields.UID??null,title:icsUnescape(fields.SUMMARY),due:`${rawDate.slice(0,4)}-${rawDate.slice(4,6)}-${rawDate.slice(6,8)}`,description:icsUnescape(fields.DESCRIPTION??''),location:icsUnescape(fields.LOCATION??''),timed:/T\d{6}/.test(fields.DTSTART??'')}}).filter(Boolean)}
document.querySelector('#calendar-export').addEventListener('click',exportCalendar);
document.querySelector('#calendar-import').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{const events=parseICS(await file.text());if(!events.length)throw new Error('No events');const timed=events.filter(item=>item.timed);const isSchoolTimetable=timed.length>20&&timed.some(item=>/Generated from (bromcom|Sims\.net)/i.test(item.description));if(isSchoolTimetable)throw new Error('School timetable already syncs through your account');let added=0;let updated=0;for(const item of events.filter(item=>!item.timed)){const existing=item.uid?state.tasks.find(t=>t.sourceKey===item.uid):null;const subject=item.description.match(/Sidequest subject:\s*([^;\n]+)/i)?.[1]?.trim()??'Calendar';const minutes=Number(item.description.match(/estimate:\s*(\d+)\s*minutes/i)?.[1]??30);const task={...(existing??{}),id:existing?.id??uid(),sourceKey:item.uid??undefined,title:item.title,subject,due:item.due,minutes,completed:existing?.completed??false,xp:existing?.xp??Math.max(20,Math.round(minutes*2)),updatedAt:Date.now(),deleted:false};if(existing){Object.assign(existing,task);updated++}else{state.tasks.push(task);added++}await put('tasks',task)}if(!added&&!updated)throw new Error('No all-day events');render();flash(`Calendar imported · ${added} added${updated?`, ${updated} updated`:''}`)}catch(error){flash(error.message||'No supported calendar events found')}finally{event.target.value=''}});
document.querySelector('#timer-toggle').addEventListener('click',e=>{if(state.timerId){clearInterval(state.timerId);state.timerId=null;e.target.textContent='Resume focus'}else{state.timerId=setInterval(()=>{state.timerSeconds=Math.max(0,state.timerSeconds-1);renderTimer();if(!state.timerSeconds){clearInterval(state.timerId);state.timerId=null;flash('Focus session complete')}},1000);e.target.textContent='Pause'}});
document.querySelector('#timer-reset').addEventListener('click',()=>{clearInterval(state.timerId);state.timerId=null;state.timerSeconds=1500;document.querySelector('#timer-toggle').textContent='Start focus';renderTimer()});
function renderTimer(){const m=String(Math.floor(state.timerSeconds/60)).padStart(2,'0');const s=String(state.timerSeconds%60).padStart(2,'0');document.querySelector('#timer').textContent=`${m}:${s}`}
window.addEventListener('online',()=>{flash('Back online · syncing');queueSync()});window.addEventListener('offline',()=>flash('Offline · changes stay safe here'));
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=15');
seed().catch(()=>flash('Local storage failed to start'));
