create table if not exists public.sidequest_tasks (
  id uuid not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  updated_at bigint not null,
  deleted boolean not null default false,
  primary key (user_id, id)
);

create index if not exists sidequest_tasks_user_updated_idx
  on public.sidequest_tasks (user_id, updated_at);

alter table public.sidequest_tasks enable row level security;
revoke all on table public.sidequest_tasks from anon, authenticated;
grant select, insert, update on table public.sidequest_tasks to authenticated;

drop policy if exists "Users read their own Sidequest tasks" on public.sidequest_tasks;
create policy "Users read their own Sidequest tasks"
  on public.sidequest_tasks for select to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users create their own Sidequest tasks" on public.sidequest_tasks;
create policy "Users create their own Sidequest tasks"
  on public.sidequest_tasks for insert to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users update their own Sidequest tasks" on public.sidequest_tasks;
create policy "Users update their own Sidequest tasks"
  on public.sidequest_tasks for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create table if not exists public.sidequest_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  updated_at bigint not null
);

alter table public.sidequest_settings enable row level security;
revoke all on table public.sidequest_settings from anon, authenticated;
grant select, insert, update on table public.sidequest_settings to authenticated;

drop policy if exists "Users read their own Sidequest settings" on public.sidequest_settings;
create policy "Users read their own Sidequest settings"
  on public.sidequest_settings for select to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users create their own Sidequest settings" on public.sidequest_settings;
create policy "Users create their own Sidequest settings"
  on public.sidequest_settings for insert to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users update their own Sidequest settings" on public.sidequest_settings;
create policy "Users update their own Sidequest settings"
  on public.sidequest_settings for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create table if not exists public.sidequest_push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null,
  p256dh text not null,
  auth text not null,
  user_agent text,
  updated_at timestamptz not null default now(),
  unique (user_id, endpoint)
);

alter table public.sidequest_push_subscriptions enable row level security;
revoke all on table public.sidequest_push_subscriptions from anon, authenticated;
grant select, insert, update, delete on table public.sidequest_push_subscriptions to authenticated;

drop policy if exists "Users manage their own Sidequest devices" on public.sidequest_push_subscriptions;
create policy "Users manage their own Sidequest devices"
  on public.sidequest_push_subscriptions for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create table if not exists public.sidequest_notification_log (
  user_id uuid not null references auth.users(id) on delete cascade,
  notification_key text not null,
  sent_at timestamptz not null default now(),
  primary key (user_id, notification_key)
);

alter table public.sidequest_notification_log enable row level security;
revoke all on table public.sidequest_notification_log from anon, authenticated;

create table if not exists public.sidequest_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  friend_code text not null unique default ('SQ-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8))),
  display_name text not null check (char_length(display_name) between 1 and 60),
  avatar_data text,
  share_lessons boolean not null default true,
  share_homework boolean not null default false,
  share_completion boolean not null default false,
  share_sparx boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.sidequest_friend_requests (
  id uuid primary key default gen_random_uuid(),
  requester_id uuid not null references auth.users(id) on delete cascade,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','declined')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (requester_id, recipient_id),
  check (requester_id <> recipient_id)
);

alter table public.sidequest_profiles enable row level security;
alter table public.sidequest_friend_requests enable row level security;
revoke all on table public.sidequest_profiles from anon, authenticated;
revoke all on table public.sidequest_friend_requests from anon, authenticated;
grant select, insert, update on table public.sidequest_profiles to authenticated;
grant select, insert, update, delete on table public.sidequest_friend_requests to authenticated;

drop policy if exists "Users manage their own Sidequest profile" on public.sidequest_profiles;
create policy "Users manage their own Sidequest profile" on public.sidequest_profiles
  for all to authenticated using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users see their Sidequest friend requests" on public.sidequest_friend_requests;
create policy "Users see their Sidequest friend requests" on public.sidequest_friend_requests
  for select to authenticated using ((select auth.uid()) in (requester_id, recipient_id));

drop policy if exists "Users send Sidequest friend requests" on public.sidequest_friend_requests;
create policy "Users send Sidequest friend requests" on public.sidequest_friend_requests
  for insert to authenticated with check ((select auth.uid()) = requester_id);

drop policy if exists "Recipients answer Sidequest friend requests" on public.sidequest_friend_requests;
create policy "Recipients answer Sidequest friend requests" on public.sidequest_friend_requests
  for update to authenticated using ((select auth.uid()) = recipient_id)
  with check ((select auth.uid()) = recipient_id);

create or replace function public.sidequest_send_friend_request(code text)
returns uuid language plpgsql security definer set search_path = public as $$
declare target uuid; request_id uuid;
begin
  select user_id into target from sidequest_profiles where upper(friend_code) = upper(trim(code));
  if target is null then raise exception 'Friend code not found'; end if;
  if target = auth.uid() then raise exception 'That is your own friend code'; end if;
  insert into sidequest_friend_requests (requester_id, recipient_id, status, updated_at)
  values (auth.uid(), target, 'pending', now())
  on conflict (requester_id, recipient_id) do update set status = 'pending', updated_at = now()
  returning id into request_id;
  return request_id;
end $$;
revoke all on function public.sidequest_send_friend_request(text) from public;
grant execute on function public.sidequest_send_friend_request(text) to authenticated;

create or replace function public.sidequest_social_state()
returns jsonb language sql security definer stable set search_path = public as $$
  select jsonb_build_object(
    'profile', (select to_jsonb(p) from sidequest_profiles p where p.user_id = auth.uid()),
    'requests', coalesce((select jsonb_agg(jsonb_build_object(
      'id', r.id, 'status', r.status, 'direction', case when r.requester_id = auth.uid() then 'outgoing' else 'incoming' end,
      'person', case when r.status = 'accepted' or r.recipient_id = auth.uid() then
        (select jsonb_build_object('user_id', p.user_id, 'display_name', p.display_name, 'avatar_data', p.avatar_data, 'friend_code', p.friend_code)
         from sidequest_profiles p where p.user_id = case when r.requester_id = auth.uid() then r.recipient_id else r.requester_id end)
      else null end
    )) from sidequest_friend_requests r where auth.uid() in (r.requester_id, r.recipient_id)), '[]'::jsonb)
  )
$$;
revoke all on function public.sidequest_social_state() from public;
grant execute on function public.sidequest_social_state() to authenticated;
