create table if not exists public.sidequest_tasks (
  id uuid not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  updated_at bigint not null,
  deleted boolean not null default false,
  primary key (user_id, id)
);

create index if not exists sidequest_tasks_user_updated_idx
  on public.sidequest_tasks (user_id, updated_at);

alter table public.sidequest_tasks enable row level security;
revoke all on table public.sidequest_tasks from anon, authenticated;
grant select, insert, update on table public.sidequest_tasks to authenticated;

drop policy if exists "Users read their own Sidequest tasks" on public.sidequest_tasks;
create policy "Users read their own Sidequest tasks"
  on public.sidequest_tasks for select to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users create their own Sidequest tasks" on public.sidequest_tasks;
create policy "Users create their own Sidequest tasks"
  on public.sidequest_tasks for insert to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users update their own Sidequest tasks" on public.sidequest_tasks;
create policy "Users update their own Sidequest tasks"
  on public.sidequest_tasks for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create table if not exists public.sidequest_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  updated_at bigint not null
);

alter table public.sidequest_settings enable row level security;
revoke all on table public.sidequest_settings from anon, authenticated;
grant select, insert, update on table public.sidequest_settings to authenticated;

drop policy if exists "Users read their own Sidequest settings" on public.sidequest_settings;
create policy "Users read their own Sidequest settings"
  on public.sidequest_settings for select to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users create their own Sidequest settings" on public.sidequest_settings;
create policy "Users create their own Sidequest settings"
  on public.sidequest_settings for insert to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users update their own Sidequest settings" on public.sidequest_settings;
create policy "Users update their own Sidequest settings"
  on public.sidequest_settings for update to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create table if not exists public.sidequest_push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null,
  p256dh text not null,
  auth text not null,
  user_agent text,
  updated_at timestamptz not null default now(),
  unique (user_id, endpoint)
);

alter table public.sidequest_push_subscriptions enable row level security;
revoke all on table public.sidequest_push_subscriptions from anon, authenticated;
grant select, insert, update, delete on table public.sidequest_push_subscriptions to authenticated;

drop policy if exists "Users manage their own Sidequest devices" on public.sidequest_push_subscriptions;
create policy "Users manage their own Sidequest devices"
  on public.sidequest_push_subscriptions for all to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create table if not exists public.sidequest_notification_log (
  user_id uuid not null references auth.users(id) on delete cascade,
  notification_key text not null,
  sent_at timestamptz not null default now(),
  primary key (user_id, notification_key)
);

alter table public.sidequest_notification_log enable row level security;
revoke all on table public.sidequest_notification_log from anon, authenticated;
